# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f3fc53aa9134c8a7ec17f436ac582b371421c6f7dbaabbc9b5ce00cbedd03da5a7237b0a660c47e5ee2b92402159896b732950892d7720445151ff15c556aee5

test:
  secret_key_base: ba5785ae171194ccfdce3c29645f0da5c0cc3d5f2ef7335f4e0a069a1d4f72d74935639ce0ca95e51cd7fcb7762126f61cf571408a66e99e821083b1167689ea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
